OPSCO_Web/Controllers/NptTrackerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OPSCO_Web.Models;
using OPSCO_Web.BL;
using PagedList;
using PagedList.Mvc;
using System.IO;
using ClosedXML.Excel;

namespace OPSCO_Web.Controllers
{
    
    public class NptTrackerController : Controller
    {
        #region Variables
        private const string module = "NPT Tracker";
        private _AppFacade _af;
        private _Access a;
        //list initialize for autocomplete
        public List<OSC_NptCategory> nptL;
        public List<OSC_Team> teamL;
        public List<OSC_Representative> repL;
        #endregion Variables
        #region Constructor
        public NptTrackerController()
        {
            this._af = new _AppFacade();
            this.a = new _Access();
            this.nptL = this._af.blNptCategory.idb;
            this.teamL = this._af.blTeam.idb;
            this.repL = this._af.blRepresentative.idb;
        }
        #endregion Constructor
        #region Method
        #region Index
        // GET: NptTracker
        public ActionResult Index(int? page, int? pageSize, bool? filterOn, _Filter filter)
        {
            #region BTSS 
            try
            {
                if (Session["role"] == null)
                    return View("~/Views/Shared/SessionTimeout.cshtml");
                else if (Session["logon_user"] == null)
                    return View("~/Views/Shared/SessionTimeout.cshtml");
                else if (Session["grp_id"] == null)
                    return View("~/Views/Shared/SessionTimeout.cshtml");
                else
                {
                    this.a = new _Access()
                    {
                        LogonUser = Session["logon_user"].ToString(),
                        Role = Session["role"].ToString(),
                        Group = Session["grp_id"].ToString(),
                        CanView = this._af.blAccess.CanView(Session["grp_id"].ToString(), module),
                        CanAdd = this._af.blAccess.CanAdd(Session["grp_id"].ToString(), module),
                        CanEdit = this._af.blAccess.CanEdit(Session["grp_id"].ToString(), module),
                        CanDelete = this._af.blAccess.CanDelete(Session["grp_id"].ToString(), module)
                    };
                    if (!this.a.CanView) return View("~/Views/Shared/NoAccess.cshtml");
                    else ViewBag.Access = this.a;
                }
            }
            catch (Exception ex)
            {
                _ErrorMessage err = new _ErrorMessage();
                err.MessageType = "Server Error - NPTTrackerController";
                err.MessageDescription = ex.Message.ToString();
                ViewBag.Error = err;
                return View("~/Views/Shared/SomethingWentWrong.cshtml");
            }
            #endregion BTSS
            #region Table
            List<OSC_ImportNPT> npts = new List<OSC_ImportNPT>();
            npts = this._af.blNpt.GetList(a);
            if (npts.Count == 0 && this._af.blNpt._err != null)
            {
                ViewBag.Error = this._af.blNpt._err;
                return View("~/Views/Shared/SomethingWentWrong.cshtml");
            }
            #endregion Table
            #region Filters
            if (filterOn != null && filterOn == true)
            {
                
            }
            else
            {
                string noVal = "";
                ViewBag.Category = noVal;
                ViewBag.Team = noVal;
                ViewBag.Representative = noVal;
                ViewBag.DateOfActivity = noVal;
                ViewBag.TimeSpent = noVal;
            }
            #endregion Filters
            #region Return
                int? defaultPageSize = 10;
                if (pageSize != null) defaultPageSize = pageSize;
                return View(npts.OrderByDescending(n => n.DateOfActivity).ToPagedList(page ?? 1, (int)defaultPageSize));
            #endregion Return
        }
        #endregion Index
        //[HttpPost]
        //public FileResult Export()
        //{
        //    #region "Initialize"
        //    af.InitializeNpts(db);
        //    #endregion "Initialize"
        //    #region "BTSS"
        //    string role;
        //    string user_name;
        //    role = Session["role"].ToString();
        //    user_name = Session["logon_user"].ToString();
        //    #endregion "BTSS"
        //    #region "TransferData"
        //    DataTable dt = new DataTable("NPT");
        //    dt.Columns.AddRange(new DataColumn[8] {
        //        new DataColumn("Team"),
        //        new DataColumn("Representative"),
        //        new DataColumn("Category"),
        //        new DataColumn("Activity Description"),
        //        new DataColumn("Date of Activity"),
        //        new DataColumn("Time Spent"),
        //        new DataColumn("Modified By"),
        //        new DataColumn("Date Modified")
        //    });
        //    var npts = (from n in db.NPT
        //                where n.Source == "Manual"
        //                select n);
        //    List<long> TeamIds = new List<long>();
        //    switch (role)
        //    {
        //        case "Manager":
        //        case "Team Leader":
        //        case "Department Analyst":
        //            foreach (OSC_ImportNPT npt in npts)
        //            {
        //                if (af.IsManaged(npt.TeamId, user_name, role))
        //                    if (!TeamIds.Contains((long)npt.TeamId))
        //                        TeamIds.Add((long)npt.TeamId);
        //            }
        //            npts = (from n in db.NPT
        //                    where n.Source == "Manual" && TeamIds.Contains((long)n.TeamId) && n.IsActive
        //                    select n);
        //            break;
        //        case "Staff":
        //            OSC_Representative oSC_Representative = af.GetRepresentativeByPRD(user_name);
        //            long repId;
        //            repId = 0;
        //            if (oSC_Representative != null)
        //            { repId = oSC_Representative.RepId; }
        //            npts = npts.Where(n => n.RepId == repId && n.IsActive);
        //            break;
        //    }
        //    string searchByCategory = "", searchByTeam = "", searchByRep = "", searchByDate = "", searchByTimeSpent ="";
        //    if ((bool)Session["NptFilter"])
        //    {
        //        searchByCategory = (string)Session["NptFilter_Category"];
        //        searchByTeam = (string)Session["NptFilter_Team"];
        //        searchByRep = (string)Session["NptFilter_Rep"];
        //        searchByDate = (string)Session["NptFilter_DoA"];
        //        searchByTimeSpent = (string)Session["NptFilter_TimeSpent"];
        //    }
        //    List<long> TeamIdResult = new List<long>();
        //    TeamIdResult = null;
        //    if (!String.IsNullOrEmpty(searchByTeam))
        //    {
        //        TeamIdResult = (from list in db.Teams where list.TeamName == searchByTeam select list.TeamId).ToList();
        //        if (role != "Admin")
        //        {
        //            TeamIdResult = (from list in db.Teams where list.TeamName == searchByTeam && list.IsActive select list.TeamId).ToList();
        //        }
        //    }
        //    List<long> RepIdResult = new List<long>();
        //    if (!String.IsNullOrEmpty(searchByRep))
        //    {
        //        RepIdResult = (from list in db.Representatives where list.FirstName + " " + list.LastName == searchByRep select list.RepId).ToList();
        //        if (role != "Admin")
        //        {
        //            RepIdResult = (from list in db.Representatives where (list.FirstName + " " + list.LastName == searchByRep) && list.IsActive select list.RepId).ToList();
        //        }
        //    }

        //    if (searchByCategory != "")
        //    {
        //        npts = npts.Where(t => t.TypeOfActivity == searchByCategory);
        //    }
        //    if (searchByTeam != "")
        //    {
        //        npts = npts.Where(t => TeamIdResult.Contains((long)t.TeamId));
        //    }
        //    if (searchByRep != "")
        //    {
        //        npts = npts.Where(t => RepIdResult.Contains((long)t.RepId));
        //    }
        //    if (searchByDate != "")
        //    {
        //        var doa = Convert.ToDateTime(searchByDate);
        //        npts = npts.Where(t => doa == t.DateOfActivity);
        //    }
        //    if (searchByTimeSpent != "")
        //    {
        //        npts = npts.Where(t => Convert.ToDouble(searchByTimeSpent) == t.TimeSpent);
        //    }
        //    if (role != "Admin")
        //    {
        //        npts = npts.Where(t => t.IsActive);
        //    }
        //    foreach (var npt in npts)
        //    {
        //        dt.Rows.Add(npt.Team.TeamName, npt.Representative.FullName, npt.TypeOfActivity, npt.Activity, npt.DateOfActivity, npt.TimeSpent, npt.UploadedBy, npt.DateUploaded);
        //    }
        //    #endregion "TransferData"
        //    #region "GenerateSpreadsheet"
        //    using (XLWorkbook wb = new XLWorkbook())
        //    {
        //        wb.Worksheets.Add(dt);
        //        using (MemoryStream stream = new MemoryStream())
        //        {
        //            wb.SaveAs(stream);
        //            return File(stream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet", "NPTList_" + DateTime.Now.ToShortDateString() + ".xlsx");
        //        }
        //    }
        //    #endregion "GenerateSpreadsheet"
        //}
        #region AutoComplete
        [HttpPost]
        public JsonResult NptCategoriesAutoComplete(string prefix)
        {

OPSCO_Web/Views/NptTracker/Create.cshtml
@model OPSCO_Web.Models.OSC_ImportNPT
@{
    ViewBag.Title = "New Record";
}
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/Site.js"></script>
<link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
<h3>NPT</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>New Record</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "NptTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Team", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>)ViewBag.Teams, "--Select Team--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_team" })
            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Representative", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("RepId", (IEnumerable<SelectListItem>)ViewBag.Representatives, "--Select Representative--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_reps" })
            @Html.ValidationMessageFor(model => model.RepId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Category", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("TypeOfActivity", (IEnumerable<SelectListItem>)ViewBag.TeamNptCategories, "--Select Category--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_category" })
            @Html.ValidationMessageFor(model => model.TypeOfActivity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Activity, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Activity, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
            @Html.ValidationMessageFor(model => model.Activity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateOfActivity, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateOfActivity, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_doa", placeholder = "MM/DD/YYYY" } })
            @Html.ValidationMessageFor(model => model.DateOfActivity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TimeSpent, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.TimeSpent, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id="txt_timespent", placeholder = "min" } })
            @Html.ValidationMessageFor(model => model.TimeSpent, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<div class="navbar navbar-default navbar-fixed-bottom table-nav">
    <div class="container-fluid">
        <div class="navbar-right navbar-form">
            <button type="submit" disabled class="btn btn-primary btn-sm pull-right" id="submit">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}
<script type="text/javascript">
    $(function () {
        validate($('#submit'));
        $('#txt_doa').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
        $('#cmb_team').change(function () {
            var url = '@Url.Action("Create")?teamId=' + $(this).val();
            window.location.href = url;
        });
        $('#txt_doa').change(function () {
            $(this).focusout();
        });
    });
</script>

OPSCO_Web/Views/NptTracker/Delete.cshtml
@model OPSCO_Web.Models.OSC_ImportNPT

@{
    ViewBag.Title = "Delete";
}

<h3>NPT Entry</h3>

<h4>Delete</h4>
<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "NptTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfActivity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfActivity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeOfActivity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeOfActivity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.IsActive)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.IsActive)
        </dd>
    </dl>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="navbar navbar-default navbar-fixed-bottom table-nav">
        <div class="container-fluid">
            <div class="navbar-right navbar-form">
                <button type="submit" class="btn btn-danger btn-sm pull-right" id="submit">
                    <i class="fa fa-trash"></i> Delete
                </button>
            </div>
        </div>
    </div>
}

OPSCO_Web/Views/NptTracker/Details.cshtml
@model OPSCO_Web.Models.OSC_ImportNPT

@{
    ViewBag.Title = "Details";
}

<h3>NPT</h3>

<div>
    <h4>Details</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "NptTracker", null)" class="btn btn-default btn-sm">
                    <i class="fa fa-chevron-left"></i> Back to List
                </a>
                @if (ViewBag.Access.CanEdit)
                {
                    <a href="@Url.Action("Edit", "NptTracker", new { id = Model.NPTReportId })" class="btn btn-default btn-sm">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
                else
                {
                    <a href="@Url.Action("Edit", "NptTracker", new { id = Model.NPTReportId })" class="btn btn-default btn-sm disabled">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
            </div>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateOfActivity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateOfActivity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TimeSpent)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TimeSpent)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.TypeOfActivity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.TypeOfActivity)
        </dd>
        @if (ViewBag.Access.Role == "Admin")
        { 
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
        }
    </dl>
</div>

OPSCO_Web/Views/NptTracker/Edit.cshtml
@model OPSCO_Web.Models.OSC_ImportNPT

@{
    ViewBag.Title = "Edit";
}
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/Site.js"></script>
<link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />

<h3>NPT</h3>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Edit</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "NptTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.NPTReportId)

    <div class="form-group">
        @Html.LabelFor(model => model.Team.TeamName, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Team.TeamName, new { htmlAttributes = new { disabled = true, @class = "form-control input-sm" } })
            @Html.HiddenFor(model => model.TeamId)
            @Html.ValidationMessageFor(model => model.Team.TeamName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Representative.FullName, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Representative.FullName, new { htmlAttributes = new { disabled = true, @class = "form-control input-sm" } })
            @Html.HiddenFor(model => model.RepId)
            @Html.ValidationMessageFor(model => model.Representative.FullName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Category", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("TypeOfActivity", (IEnumerable<SelectListItem>)ViewBag.TeamNptCategories, "--Select Category--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_category" })
            @Html.ValidationMessageFor(model => model.TypeOfActivity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Activity, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Activity, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
            @Html.ValidationMessageFor(model => model.Activity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateOfActivity, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateOfActivity, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_doa", placeholder = "MM/DD/YYYY" } })
            @Html.ValidationMessageFor(model => model.DateOfActivity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.TimeSpent, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.TimeSpent, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", placeholder = "min" } })
            @Html.ValidationMessageFor(model => model.TimeSpent, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (ViewBag.Access.Role == "Admin")
    {
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
            <div class="col-md-4">
                <div class="checkbox">

                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }
</div>
    <div class="navbar navbar-default navbar-fixed-bottom table-nav">
        <div class="container-fluid">
            <div class="navbar-right navbar-form">
                <button type="submit" disabled class="btn btn-primary btn-sm pull-right" id="submit">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}
<script type="text/javascript">
$(function () {
    validate($('#submit'));
    $('#txt_doa').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
    $('#txt_doa').change(function () {
        $(this).focusout();
    });
});
</script>