OPSCO_Web/Controllers/ManualEntryController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OPSCO_Web.Models;
using OPSCO_Web.BL;
using PagedList;
using PagedList.Mvc;

namespace OPSCO_Web.Controllers
{
    public class ManualEntryController : Controller
    {
        private OSCContext db = new OSCContext();
        private AppFacade af = new AppFacade();

        // GET: ManualEntry
        public ActionResult Index(int? page, int? pageSize, string searchString)
        {
            #region "Initialize"
            af.InitializeManualEntries(db);
            #endregion "Initialize"
            #region "BTSS"
            string role;
            string user_name;
            try
            {
                role = Session["role"].ToString();
                user_name = Session["logon_user"].ToString();
                string grp_id = Session["grp_id"].ToString();
                ViewBag.CanView = af.CanView(grp_id, "Manual Entries");
                ViewBag.CanAdd = af.CanAdd(grp_id, "Manual Entries");
                ViewBag.CanEdit = af.CanEdit(grp_id, "Manual Entries");
                ViewBag.CanDelete = af.CanDelete(grp_id, "Manual Entries");

                if (!ViewBag.CanView) return HttpNotFound();
            }
            catch (Exception exception)
            {
                //session expired
                string result = exception.Message.ToString();
                return HttpNotFound();
            }

            var mes = (from m in db.ManualEntries
                       select m);
            List<long> TeamIds = new List<long>();
            switch (role)
            {
                case "Manager":
                case "Team Leader":
                case "Department Analyst":
                    foreach (OSC_ManualEntry obj in mes)
                    {
                        if (af.IsManaged(obj.TeamId, user_name, role))
                            if (!TeamIds.Contains((long)obj.TeamId))
                                TeamIds.Add((long)obj.TeamId);
                    }
                    mes = (from m in db.ManualEntries
                            where TeamIds.Contains((long)m.TeamId) && m.IsActive == true
                            select m);
                    break;
                case "Staff":
                    OSC_Representative oSC_Representative = af.GetRepresentativeByPRD(user_name);
                    long repId;
                    repId = 0;
                    if (oSC_Representative != null)
                    { repId = oSC_Representative.RepId; }
                    mes = mes.Where(m => m.RepId == repId && m.IsActive);
                    break;
            }
            #endregion "BTSS"
            #region "Table"
            int? defaultPageSize = 10;
            if (pageSize != null) defaultPageSize = pageSize;
            if (!String.IsNullOrEmpty(searchString)) mes = mes.Where(m => m.MonthName.Contains(searchString) || m.Year.ToString().Contains(searchString));
            #endregion "Table"
            #region "Return"
            return View(mes.OrderByDescending(m => m.Year).ThenByDescending(m => m.Month).ThenByDescending(m => m.TeamId).ToPagedList(page ?? 1, (int)defaultPageSize));
            #endregion "Return"
        }

        // GET: ManualEntry/Details/5
        public ActionResult Details(long? id)
        {
            #region "BTSS"
            string role;
            string user_name;
            try
            {
                role = Session["role"].ToString();
                user_name = Session["logon_user"].ToString();
                string grp_id = Session["grp_id"].ToString();
                ViewBag.CanView = af.CanView(grp_id, "Manual Entries");
                ViewBag.CanEdit = af.CanEdit(grp_id, "Manual Entries");
                if (!ViewBag.CanView) return HttpNotFound();
            }
            catch (Exception exception)
            {
                string result = exception.Message.ToString();
                return HttpNotFound();
            }
            #endregion "BTSS"
            #region "Method"
            if (id == null) return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            OSC_ManualEntry oSC_ManualEntry = db.ManualEntries.Find(id);
            if (oSC_ManualEntry == null) return HttpNotFound();
            if (!af.IsManaged(oSC_ManualEntry.TeamId, user_name, role)) return HttpNotFound();
            oSC_ManualEntry.Team = db.Teams.Find(oSC_ManualEntry.TeamId);
            oSC_ManualEntry.Representative = db.Representatives.Find(oSC_ManualEntry.RepId);
            oSC_ManualEntry.Representative.FullName = oSC_ManualEntry.Representative.FirstName + " " + oSC_ManualEntry.Representative.LastName;
            oSC_ManualEntry.PeriodCoverage = Convert.ToDateTime(oSC_ManualEntry.Month + "/1/" + oSC_ManualEntry.Year);
            #endregion "Method"
            #region "Return"
            return View(oSC_ManualEntry);
            #endregion "Return"
        }

        // GET: ManualEntry/Create
        public ActionResult Create(long? teamId)
        {
            #region "BTSS"
            string role;
            string user_name;
            try
            {
                role = Session["role"].ToString();
                user_name = Session["logon_user"].ToString();
                string grp_id = Session["grp_id"].ToString();
                ViewBag.CanAdd = af.CanAdd(grp_id, "Manual Entries");
                if (!ViewBag.CanAdd) return HttpNotFound();
            }
            catch (Exception exception)
            {
                string result = exception.Message.ToString();
                return HttpNotFound();
            }
            #endregion "BTSS"
            #region "Initialize"
            af.InitializeRepresentatives(db);
            #endregion "Initialize"
            #region "ViewBagProjectResponsibilities"
            ViewBag.ProjectResponsibilities = db.projectResponsibilities;
            #endregion "ViewBagProjectResponsibilities"
            #region "ViewBagTeams"
            switch (role)
            {
                case "Admin":
                    ViewBag.Teams = new SelectList(db.Teams, "TeamId", "TeamName");
                    break;
                case "Manager":
                case "Team Leader":
                case "Department Analyst":
                    List<long> TeamIds = new List<long>();
                    foreach (OSC_Team team in db.Teams)
                    {
                        if (af.IsManaged(team.TeamId, user_name, role))
                            if (!TeamIds.Contains(team.TeamId))
                                TeamIds.Add(team.TeamId);
                    }
                    ViewBag.Teams = new SelectList(db.Teams.Where(x => TeamIds.Contains(x.TeamId) && x.IsActive), "TeamId", "TeamName");
                    break;
                case "Staff":
                    long repTeamId = (long)af.GetRepresentativeByPRD(user_name).TeamId;
                    ViewBag.Teams = new SelectList(db.Teams.Where(t => t.TeamId == repTeamId), "TeamId", "TeamName");
                    break;
            }
            #endregion "ViewBagTeams"
            #region "ViewBagRepresentative"
            long defaultTeamId = 0;
            var reps = (from r in db.Representatives select r);
            if (teamId != null)
            {
                long repIdd = af.GetRepresentativeByPRD(user_name).RepId;
                switch (role)
                {
                    case "Admin":
                        reps = reps.Where(r => r.TeamId == teamId);
                        break;
                    case "Manager":
                    case "Team Leader":
                    case "Department Analyst":
                        reps = reps.Where(r => r.TeamId == teamId && r.IsActive);
                        break;
                    case "Staff":
                        reps = reps.Where(r => r.TeamId == teamId && r.RepId == repIdd && r.IsActive);
                        break;
                }
            }
            else
            {
                reps = reps.Where(r => r.TeamId == defaultTeamId);
            }
            ViewBag.Representatives = new SelectList(reps, "RepId", "FullName");
            #endregion "ViewBagRepresentative"
            #region "Return"
            return View();
            #endregion "Return"
        }

        // POST: ManualEntry/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "EntryId,TeamId,RepId,GainLossOccurances,GainLossAmount,CallManagementScore,ProjectResponsibility,ScheduleAdherence,Compliance,ProductAccuracy,Commitment,JHValues,CallEfficiency,Engagement,AdministrativeProcedures,Month,Year,DateUploaded,UploadedBy,IsActive,ActiveProjects,CompletedProjects,PeriodCoverage")] OSC_ManualEntry oSC_ManualEntry)
        {
            #region "BTSS"
            string role;
            string user_name;
            try
            {
                role = Session["role"].ToString();
                user_name = Session["logon_user"].ToString();
                string grp_id = Session["grp_id"].ToString();
                ViewBag.CanAdd = af.CanAdd(grp_id, "Manual Entries");
                if (!ViewBag.CanAdd) return HttpNotFound();
            }
            catch (Exception exception)
            {
                string result = exception.Message.ToString();
                return HttpNotFound();
            }
            #endregion "BTSS"
            #region "AddValues"
            oSC_ManualEntry.Month = Convert.ToDateTime(oSC_ManualEntry.PeriodCoverage).Month;
            oSC_ManualEntry.Year = Convert.ToDateTime(oSC_ManualEntry.PeriodCoverage).Year;

OPSCO_Web/Views/ManualEntry/Create.cshtml
@model OPSCO_Web.Models.OSC_ManualEntry
@{
    ViewBag.Title = "New Record";
}
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/Site.js"></script>
<link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
<h3>Manual Entry</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>New Record</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "ManualEntry", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <div class="form-group">
        @Html.Label("Team", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>)ViewBag.Teams, "--Select Team--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_team" })
            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Representative", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("RepId", (IEnumerable<SelectListItem>)ViewBag.Representatives, "--Select Representative--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_reps" })
            @Html.ValidationMessageFor(model => model.RepId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Period Coverage", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.PeriodCoverage, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_dtcvg", placeholder = "MM/DD/YYYY" } })
            @Html.ValidationMessageFor(model => model.PeriodCoverage, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.GainLossOccurances, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.GainLossOccurances, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.GainLossOccurances, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.GainLossAmount, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.GainLossAmount, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.GainLossAmount, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.CallManagementScore, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CallManagementScore, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.CallManagementScore, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.ProjectResponsibility, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.DropDownList("ProjectResponsibility", (IEnumerable<SelectListItem>)ViewBag.ProjectResponsibilities, "--Select--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled" })
                    @Html.ValidationMessageFor(model => model.ProjectResponsibility, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.ScheduleAdherence, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.ScheduleAdherence, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.ScheduleAdherence, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Compliance, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Compliance, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.Compliance, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.ProductAccuracy, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.ProductAccuracy, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.ProductAccuracy, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Commitment, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Commitment, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.Commitment, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.JHValues, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.JHValues, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.JHValues, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.CallEfficiency, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CallEfficiency, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.CallEfficiency, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.Engagement, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.Engagement, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.Engagement, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.AdministrativeProcedures, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.AdministrativeProcedures, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.AdministrativeProcedures, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.ActiveProjects, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.ActiveProjects, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.ActiveProjects, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                @Html.LabelFor(model => model.CompletedProjects, htmlAttributes: new { @class = "control-label input-sm col-md-6" })
                <div class="col-md-6">
                    @Html.EditorFor(model => model.CompletedProjects, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled" } })
                    @Html.ValidationMessageFor(model => model.CompletedProjects, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-default navbar-fixed-bottom table-nav">
    <div class="container-fluid">
        <div class="navbar-right navbar-form">
            <button type="submit" disabled class="btn btn-primary btn-sm pull-right" id="submit">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
$(function () {
    validate($('#submit'));
    $('#txt_dtcvg').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
    $('#cmb_team').change(function () {
        var url = '@Url.Action("Create")?teamId=' + $(this).val();
        window.location.href = url;
    });
    $('#txt_dtcvg').change(function () {
        $(this).focusout();
    });
});
</script>

OPSCO_Web/Views/ManualEntry/Delete.cshtml
@model OPSCO_Web.Models.OSC_ManualEntry
@{
    ViewBag.Title = "Delete";
}
<h3>Manual Entry</h3>
<h4>Delete</h4>
<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "ManualEntry", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PeriodCoverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeriodCoverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GainLossOccurances)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GainLossOccurances)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GainLossAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GainLossAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CallManagementScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CallManagementScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectResponsibility)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectResponsibility)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleAdherence)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleAdherence)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Compliance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Compliance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductAccuracy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductAccuracy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Commitment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Commitment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JHValues)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JHValues)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CallEfficiency)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CallEfficiency)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Engagement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Engagement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AdministrativeProcedures)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AdministrativeProcedures)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveProjects)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActiveProjects)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CompletedProjects)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompletedProjects)
        </dd>
        @if (Session["role"].ToString() == "Admin")
        { 
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
        }
    </dl>

</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="navbar navbar-default navbar-fixed-bottom table-nav">
        <div class="container-fluid">
            <div class="navbar-right navbar-form">
                <button type="submit" class="btn btn-danger btn-sm pull-right" id="submit">
                    <i class="fa fa-trash"></i> Delete
                </button>
            </div>
        </div>
    </div>
}

OPSCO_Web/Views/ManualEntry/Details.cshtml
@model OPSCO_Web.Models.OSC_ManualEntry

@{
    ViewBag.Title = "Details";
}
<h3>Manual Entry</h3>
<div>
    <h4>Details</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "ManualEntry", null)" class="btn btn-default btn-sm">
                    <i class="fa fa-chevron-left"></i> Back to List
                </a>
                @if (ViewBag.CanEdit)
                { 
                    <a href="@Url.Action("Edit", "ManualEntry", new { id = Model.EntryId } )" class="btn btn-default btn-sm">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
                else
                { 
                    <a href="@Url.Action("Edit", "ManualEntry", new { id = Model.EntryId } )" class="btn btn-default btn-sm disabled">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
            </div>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.PeriodCoverage)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.PeriodCoverage)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GainLossOccurances)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GainLossOccurances)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.GainLossAmount)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.GainLossAmount)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CallManagementScore)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CallManagementScore)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProjectResponsibility)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProjectResponsibility)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ScheduleAdherence)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ScheduleAdherence)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Compliance)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Compliance)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ProductAccuracy)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ProductAccuracy)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Commitment)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Commitment)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.JHValues)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.JHValues)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CallEfficiency)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CallEfficiency)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Engagement)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Engagement)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.AdministrativeProcedures)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.AdministrativeProcedures)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.ActiveProjects)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.ActiveProjects)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.CompletedProjects)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.CompletedProjects)
        </dd>
        @if (Session["role"].ToString() == "Admin")
        {
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
        }
    </dl>

</div>