OPSCO_Web/Controllers/ActivityTrackerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using OPSCO_Web.Models;
using OPSCO_Web.BL;
using PagedList;
using PagedList.Mvc;
using System.IO;
using ClosedXML.Excel;

namespace OPSCO_Web.Controllers
{
    public class ActivityTrackerController : Controller
    {
        private OSCContext db = new OSCContext();
        private AppFacade af = new AppFacade();

        // GET: ActivityTracker
        public ActionResult Index(int? page, int? pageSize, string searchByActivity, string searchByTeam, string searchByRep, string searchByDateFrom, string searchByDateTo)
        {
            #region "Initialize"
            af.InitializeActivities(db);
            #endregion "Initialize"
            #region "BTSS"
            string role;
            string user_name;
            try
            {
                role = Session["role"].ToString();
                user_name = Session["logon_user"].ToString();
                string grp_id = Session["grp_id"].ToString();
                ViewBag.CanView = af.CanView(grp_id, "Activity Tracker");
                ViewBag.CanAdd = af.CanAdd(grp_id, "Activity Tracker");
                ViewBag.CanEdit = af.CanEdit(grp_id, "Activity Tracker");
                ViewBag.CanDelete = af.CanDelete(grp_id, "Activity Tracker");

                if (!ViewBag.CanView) return HttpNotFound();
            }
            catch (Exception exception)
            {
                //session expired
                string result = exception.Message.ToString();
                return HttpNotFound();
            }

            var acts = (from a in db.ActivityTrackers
                        where a.Activity != "Attendance"
                        select a);
            List<long> TeamIds = new List<long>();
            switch (role)
            {
                case "Manager":
                case "Team Leader":
                case "Department Analyst":
                    foreach (OSC_ActivityTracker obj in acts)
                    {
                        if (af.IsManaged(obj.TeamId, user_name, role))
                            if (!TeamIds.Contains(obj.TeamId))
                                TeamIds.Add(obj.TeamId);
                    }
                    acts = (from a in db.ActivityTrackers
                            where a.Activity != "Attendance" && TeamIds.Contains(a.TeamId) && a.IsActive
                            select a);
                    break;
                case "Staff":
                    OSC_Representative oSC_Representative = af.GetRepresentativeByPRD(user_name);
                    long repId;
                    repId = 0;
                    if (oSC_Representative != null)
                    { repId = oSC_Representative.RepId; }
                    acts = acts.Where(a => a.RepId == repId && a.IsActive);
                    break;
            }
            #endregion "BTSS"
            #region "Table"
            int? defaultPageSize = 10;
            if (pageSize != null) defaultPageSize = pageSize;
            if (searchByActivity != null || searchByTeam != null || searchByRep != null || searchByDateFrom != null || searchByDateTo != null)
            {
                Session["ActivityFilter"] = true;
                List<long> TeamIdResult = new List<long>();
                TeamIdResult = null;
                if (!String.IsNullOrEmpty(searchByTeam))
                {
                    TeamIdResult = (from list in db.Teams where list.TeamName == searchByTeam select list.TeamId).ToList();
                    if (role != "Admin")
                    {
                        TeamIdResult = (from list in db.Teams where list.TeamName == searchByTeam && list.IsActive select list.TeamId).ToList();
                    }
                }
                List<long> RepIdResult = new List<long>();
                if (!String.IsNullOrEmpty(searchByRep))
                {
                    RepIdResult = (from list in db.Representatives where list.FirstName + " " + list.LastName == searchByRep select list.RepId).ToList();
                    if (role != "Admin")
                    {
                        RepIdResult = (from list in db.Representatives where (list.FirstName + " " + list.LastName == searchByRep) && list.IsActive select list.RepId).ToList();
                    }
                }

                if (searchByActivity != "")
                {
                    acts = acts.Where(t => t.Activity == searchByActivity);
                }
                if (searchByTeam != "")
                {
                    acts = acts.Where(t => TeamIdResult.Contains((long)t.TeamId));
                }
                if (searchByRep != "")
                {
                    acts = acts.Where(t => RepIdResult.Contains((long)t.RepId));
                }
                if (searchByDateFrom != "")
                {
                    var dt = Convert.ToDateTime(searchByDateFrom);
                    acts = acts.Where(t => dt == t.DateFrom);
                }
                if (searchByDateTo != "")
                {
                    var dt = Convert.ToDateTime(searchByDateTo);
                    acts = acts.Where(t => dt == t.DateTo);
                }
                if (role != "Admin")
                {
                    acts = acts.Where(t => t.IsActive);
                }
            }
            #endregion "Table"
            #region "ViewBagFilters"
            if (searchByActivity != null)
            {
                Session["ActivityFilter_Activity"] = searchByActivity;
                ViewBag.Activity = searchByActivity;
            }
            else
            {
                Session["ActivityFilter_Activity"] = "";
                ViewBag.Activity = "";
            }
            if (searchByTeam != null)
            {
                Session["ActivityFilter_Team"] = searchByTeam;
                ViewBag.Team = searchByTeam;
            }
            else
            {
                Session["ActivityFilter_Team"] = "";
                ViewBag.Team = "";
            }
            if (searchByRep != null)
            {
                Session["ActivityFilter_Rep"] = searchByRep;
                ViewBag.Representative = searchByRep;
            }
            else
            {
                Session["ActivityFilter_Rep"] = "";
                ViewBag.Representative = "";
            }
            if (searchByDateFrom != null)
            {
                Session["ActivityFilter_DateFrom"] = searchByDateFrom;
                ViewBag.DateFrom = searchByDateFrom;
            }
            else
            {
                Session["ActivityFilter_DateFrom"] = "";
                ViewBag.DateFrom = "";
            }
            if (searchByDateTo != null)
            {
                Session["ActivityFilter_DateTo"] = searchByDateTo;
                ViewBag.DateTo = searchByDateTo;
            }
            else
            {
                Session["ActivityFilter_DateTo"] = "";
                ViewBag.DateTo = "";
            }
            #endregion"ViewBagFilters"
            #region "Return"
            return View(acts.OrderByDescending(a => a.Year).ThenByDescending(a => a.Month).ThenByDescending(a => a.TeamId).ToPagedList(page ?? 1, (int)defaultPageSize));
            #endregion "Return"
        }

        public FileResult Export()
        {
            #region "Initialize"
            af.InitializeActivities(db);
            #endregion "Initialize"
            #region "BTSS"
            string role;
            string user_name;
            role = Session["role"].ToString();
            user_name = Session["logon_user"].ToString();
            #endregion "BTSS"
            #region "TransferData"
            DataTable dt = new DataTable("Activities");
            dt.Columns.AddRange(new DataColumn[9] {
                new DataColumn("Team"),
                new DataColumn("Representative"),
                new DataColumn("Activity"),
                new DataColumn("Date From"),
                new DataColumn("Date To"),
                new DataColumn("No of Hours"),
                new DataColumn("No of Days"),
                new DataColumn("Modified By"),
                new DataColumn("Date Modified")
            });
            var acts = (from a in db.ActivityTrackers
                        where a.Activity != "Attendance"
                        select a);
            List<long> TeamIds = new List<long>();
            switch (role)
            {
                case "Manager":
                case "Team Leader":
                case "Department Analyst":
                    foreach (OSC_ActivityTracker obj in acts)
                    {
                        if (af.IsManaged(obj.TeamId, user_name, role))
                            if (!TeamIds.Contains(obj.TeamId))
                                TeamIds.Add(obj.TeamId);
                    }
                    acts = (from a in db.ActivityTrackers
                            where a.Activity != "Attendance" && TeamIds.Contains(a.TeamId) && a.IsActive
                            select a);
                    break;
                case "Staff":
                    OSC_Representative oSC_Representative = af.GetRepresentativeByPRD(user_name);
                    long repId;
                    repId = 0;
                    if (oSC_Representative != null)
                    { repId = oSC_Representative.RepId; }
                    acts = acts.Where(a => a.RepId == repId && a.IsActive);
                    break;
            }
            string searchByActivity = "", searchByTeam = "", searchByRep = "", searchByDateFrom = "", searchByDateTo = "";
            if ((bool)Session["ActivityFilter"])
            {
                searchByActivity = (string)Session["ActivityFilter_Activity"];

OPSCO_Web/Views/ActivityTracker/Create.cshtml
@model OPSCO_Web.Models.OSC_ActivityTracker
@{
    ViewBag.Title = "New Record";
}
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/moment.js"></script>
<script src="~/Scripts/Site.js"></script>
<link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
<h3>Activity</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
<div class="form-horizontal">
    <h4>New Record</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "ActivityTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    <input type="hidden" id="hid_workhours" value="@ViewBag.WorkHours" />
    <div class="form-group">
        @Html.Label("Team", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("TeamId", (IEnumerable<SelectListItem>)ViewBag.Teams, "--Select Team--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_team" })
            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Representative", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("RepId", (IEnumerable<SelectListItem>)ViewBag.Representatives, "--Select Representative--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_reps" })
            @Html.ValidationMessageFor(model => model.RepId, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.Label("Activity", htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownList("Activity", (IEnumerable<SelectListItem>)ViewBag.Activities, "--Select Activity--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_activity" })
            @Html.ValidationMessageFor(model => model.Activity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", placeholder = "MM/DD/YYYY", id = "txt_dtfrom" } })
            @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", placeholder = "MM/DD/YYYY", id = "txt_dtto" } })
            @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NoOfDays, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.NoOfDays, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", placeholder = "days", id = "txt_days" } })
            @Html.ValidationMessageFor(model => model.NoOfDays, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NoOfHours, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.NoOfHours, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", placeholder = "hours", id="txt_hours" } })
            @Html.ValidationMessageFor(model => model.NoOfHours, "", new { @class = "text-danger" })
        </div>
    </div>
</div>
<div class="navbar navbar-default navbar-fixed-bottom table-nav">
    <div class="container-fluid">
        <div class="navbar-right navbar-form">
            <button type="submit" disabled class="btn btn-primary btn-sm pull-right" id="submit">
                <i class="fa fa-save"></i> Save
            </button>
        </div>
    </div>
</div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
<script type="text/javascript">
    $(function () {
        validate($('#submit'));
        $('#txt_dtfrom').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
        $('#txt_dtto').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
        $('#cmb_team').change(function () {
            var url = '@Url.Action("Create")?teamId=' + $(this).val();
            window.location.href = url;
        });
        $('#cmb_reps').change(function () {
            var url = '@Url.Action("Create")?teamId=' + $('#cmb_team').val() + '&repId=' + $(this).val();
            window.location.href = url;
        });
        $('#txt_dtfrom').change(function () {
            calculate();
            $(this).focusout();
        });
        $('#txt_dtto').change(function () {
            calculate();
            $(this).focusout();
        });

        function calculate() {
            var workHours = $('#hid_workhours').val();
            if ($('#txt_dtfrom').val() != '' && $('#txt_dtto').val() != '') {
                var diff = 0;
                var d1 = moment($('#txt_dtfrom').val(), 'M/D/YYYY');
                var d2 = moment($('#txt_dtto').val(), 'M/D/YYYY');
                var diff = d2.diff(d1, 'days');
                diff += 1;
                var act = $('#cmb_activity').val();
                switch (act) {
                    case 'Time-off':
                    case 'Holiday':
                        var excWkDay = diff % 7;              //Get excess weekday
                        var wkDay = diff - excWkDay;          //Remove excess from result
                        var wk = wkDay / 7;                     //count number of weeks
                        if (wk > 0) {
                            wk = Math.floor(wk) * 2;            //Multiply to two to include both sat and sun
                            diff = diff - wk;
                        }
                        break;
                    case null:
                        diff = 0;
                        break;
                }
                $('#txt_days').val(diff);
                $('#txt_hours').val(workHours * diff);
            }
        }
    });
</script>

OPSCO_Web/Views/ActivityTracker/Delete.cshtml
@model OPSCO_Web.Models.OSC_ActivityTracker
@{
    ViewBag.Title = "Delete";
}
<h3>Activity</h3>
<h4>Delete</h4>
<div>
    <h4>Are you sure you want to delete this?</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "ActivityTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateFrom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateFrom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoOfHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoOfHours)
        </dd>
        @if (Session["role"].ToString() == "Admin")
        { 
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
        }
    </dl>
</div>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    <div class="navbar navbar-default navbar-fixed-bottom table-nav">
        <div class="container-fluid">
            <div class="navbar-right navbar-form">
                <button type="submit" class="btn btn-danger btn-sm pull-right" id="submit">
                    <i class="fa fa-trash"></i> Delete
                </button>
            </div>
        </div>
    </div>
}

OPSCO_Web/Views/ActivityTracker/Details.cshtml
@model OPSCO_Web.Models.OSC_ActivityTracker
@{
    ViewBag.Title = "Details";
}
<h3>Activity</h3>
<div>
    <h4>Details</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <div class="btn-group">
                <a href="@Url.Action("Index", "ActivityTracker", null)" class="btn btn-default btn-sm">
                    <i class="fa fa-chevron-left"></i> Back to List
                </a>
                @if (ViewBag.CanEdit)
                { 
                    <a href="@Url.Action("Edit", "ActivityTracker", new { id = Model.ActivityId } )" class="btn btn-default btn-sm">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
                else
                { 
                    <a href="@Url.Action("Edit", "ActivityTracker", new { id = Model.ActivityId } )" class="btn btn-default btn-sm disabled">
                        <i class="fa fa-edit"></i> Edit
                    </a>
                }
            </div>
        </div>
    </div>
    <br />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Activity)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Activity)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Representative.FullName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Representative.FullName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Team.TeamName)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Team.TeamName)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateFrom)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateFrom)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.DateTo)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.DateTo)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoOfDays)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoOfDays)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.NoOfHours)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.NoOfHours)
        </dd>
        @if (Session["role"].ToString() == "Admin")
        {
            <dt>
                @Html.DisplayNameFor(model => model.IsActive)
            </dt>
            <dd>
                @Html.DisplayFor(model => model.IsActive)
            </dd>
        }
    </dl>
</div>

OPSCO_Web/Views/ActivityTracker/Edit.cshtml
@model OPSCO_Web.Models.OSC_ActivityTracker
@{
    ViewBag.Title = "Edit";
}
<script src="~/Scripts/jquery-3.2.1.js"></script>
<script src="~/Scripts/jquery-ui-1.12.1.js"></script>
<script src="~/Scripts/moment.js"></script>
<script src="~/Scripts/Site.js"></script>
<link rel="stylesheet" href="~/Content/themes/base/jquery-ui.css" />
<h3>Activity</h3>
@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()

<div class="form-horizontal">
    <h4>Edit</h4>
    <hr />
    <div class="row">
        <div class="col-md-12">
            <a href="@Url.Action("Index", "ActivityTracker", null)" class="btn btn-default btn-sm">
                <i class="fa fa-chevron-left"></i> Back to List
            </a>
        </div>
    </div>
    <br />
    @Html.ValidationSummary(true, "", new { @class = "text-danger" })
    @Html.HiddenFor(model => model.ActivityId)
    @Html.HiddenFor(model => model.Representative.WorkHours, new { id = "hid_workhours" })
    <div class="form-group">
        @Html.LabelFor(model => model.Team.TeamName, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Team.TeamName, new { htmlAttributes = new { disabled = true, @class = "form-control input-sm" } })
            @Html.HiddenFor(model => model.TeamId)
            @Html.ValidationMessageFor(model => model.Team.TeamName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Representative.FullName, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.Representative.FullName, new { htmlAttributes = new { disabled = true, @class = "form-control input-sm" } })
            @Html.HiddenFor(model => model.RepId)
            @Html.ValidationMessageFor(model => model.Representative.FullName, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.Activity, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.DropDownListFor(model => model.Activity, (IEnumerable<SelectListItem>)ViewBag.Activities, "--Select Activity--", htmlAttributes: new { @class = "form-control input-sm input-required unfilled", id = "cmb_activity" })
            @Html.ValidationMessageFor(model => model.Activity, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateFrom, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateFrom, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_dtfrom" } })
            @Html.ValidationMessageFor(model => model.DateFrom, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.DateTo, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.DateTo, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_dtto" } })
            @Html.ValidationMessageFor(model => model.DateTo, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NoOfDays, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.NoOfDays, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_days" } })
            @Html.ValidationMessageFor(model => model.NoOfDays, "", new { @class = "text-danger" })
        </div>
    </div>
    <div class="form-group">
        @Html.LabelFor(model => model.NoOfHours, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
        <div class="col-md-4">
            @Html.EditorFor(model => model.NoOfHours, new { htmlAttributes = new { @class = "form-control input-sm input-required unfilled", id = "txt_hours" } })
            @Html.ValidationMessageFor(model => model.NoOfHours, "", new { @class = "text-danger" })
        </div>
    </div>
    @if (Session["role"].ToString() == "Admin")
    {
        <div class="form-group">
            @Html.LabelFor(model => model.IsActive, htmlAttributes: new { @class = "control-label input-sm col-md-2" })
            <div class="col-md-4">
                <div class="checkbox">

                    @Html.EditorFor(model => model.IsActive)
                    @Html.ValidationMessageFor(model => model.IsActive, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>
    }
</div>
    <div class="navbar navbar-default navbar-fixed-bottom table-nav">
        <div class="container-fluid">
            <div class="navbar-right navbar-form">
                <button type="submit" disabled class="btn btn-primary btn-sm pull-right" id="submit">
                    <i class="fa fa-save"></i> Save
                </button>
            </div>
        </div>
    </div>
}
@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}
    <script type="text/javascript">
    $(function () {
        validate($('#submit'));
        $('#txt_dtfrom').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
        $('#txt_dtto').datepicker({ format: 'mm/dd/yy', showAnim: 'drop' });
        $('#txt_dtfrom').change(function () {
            calculate();
            $(this).focusout();
        });
        $('#txt_dtto').change(function () {
            calculate();
            $(this).focusout();
        });

        function calculate() {
            var workHours = $('#hid_workhours').val();
            if ($('#txt_dtfrom').val() != '' && $('#txt_dtto').val() != '') {
                var diff = 0;
                var d1 = moment($('#txt_dtfrom').val(), 'M/D/YYYY');
                var d2 = moment($('#txt_dtto').val(), 'M/D/YYYY');
                var diff = d2.diff(d1, 'days');
                diff += 1;
                var act = $('#cmb_activity').val();
                switch (act) {
                    case 'Time-off':
                    case 'Holiday':
                        var excWkDay = diff % 7;              //Get excess weekday
                        var wkDay = diff - excWkDay;          //Remove excess from result
                        var wk = wkDay / 7;                     //count number of weeks
                        if (wk > 0) {
                            wk = Math.floor(wk) * 2;            //Multiply to two to include both sat and sun
                            diff = diff - wk;
                        }
                        break;
                    case null:
                        diff = 0;
                        break;
                }
                $('#txt_days').val(diff);
                $('#txt_hours').val(workHours * diff);
            }
        }
    });
    </script>